try {
    console.log(a);
    let a = 1;
    a/0
}
catch (err){
console.log ("на ноль делить нельзя");}